export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";
export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const SET_USER_PHONENUMBER = "SET_USER_PHONENUMBER";
export const SET_USER_LOCATION = "SET_USER_LOCATION";
